/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCheckoutIdRouteImport } from './routes/c.$checkoutId'
import { Route as CollabCheckoutIdRouteImport } from './routes/collab.$checkoutId'
import { Route as WCheckoutIdRouteImport } from './routes/w.$checkoutId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCheckoutIdRoute = CCheckoutIdRouteImport.update({
  id: '/c/$checkoutId',
  path: '/c/$checkoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabCheckoutIdRoute = CollabCheckoutIdRouteImport.update({
  id: '/collab/$checkoutId',
  path: '/collab/$checkoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const WCheckoutIdRoute = WCheckoutIdRouteImport.update({
  id: '/w/$checkoutId',
  path: '/w/$checkoutId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/c/$checkoutId': typeof CCheckoutIdRoute
  '/collab/$checkoutId': typeof CollabCheckoutIdRoute
  '/w/$checkoutId': typeof WCheckoutIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/c/$checkoutId': typeof CCheckoutIdRoute
  '/collab/$checkoutId': typeof CollabCheckoutIdRoute
  '/w/$checkoutId': typeof WCheckoutIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/c/$checkoutId': typeof CCheckoutIdRoute
  '/collab/$checkoutId': typeof CollabCheckoutIdRoute
  '/w/$checkoutId': typeof WCheckoutIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/c/$checkoutId' | '/collab/$checkoutId' | '/w/$checkoutId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/c/$checkoutId' | '/collab/$checkoutId' | '/w/$checkoutId'
  id:
    | '__root__'
    | '/'
    | '/c/$checkoutId'
    | '/collab/$checkoutId'
    | '/w/$checkoutId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CCheckoutIdRoute: typeof CCheckoutIdRoute
  CollabCheckoutIdRoute: typeof CollabCheckoutIdRoute
  WCheckoutIdRoute: typeof WCheckoutIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$checkoutId': {
      id: '/c/$checkoutId'
      path: '/c/$checkoutId'
      fullPath: '/c/$checkoutId'
      preLoaderRoute: typeof CCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collab/$checkoutId': {
      id: '/collab/$checkoutId'
      path: '/collab/$checkoutId'
      fullPath: '/collab/$checkoutId'
      preLoaderRoute: typeof CollabCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/w/$checkoutId': {
      id: '/w/$checkoutId'
      path: '/w/$checkoutId'
      fullPath: '/w/$checkoutId'
      preLoaderRoute: typeof WCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CCheckoutIdRoute: CCheckoutIdRoute,
  CollabCheckoutIdRoute: CollabCheckoutIdRoute,
  WCheckoutIdRoute: WCheckoutIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
